"""
Converts settings.yaml into a C header that embeds its content as a string
literal.  Run automatically by build.bat before compilation.
"""
import sys
import os

src  = os.path.join(os.path.dirname(__file__), "settings.yaml")
dst  = os.path.join(os.path.dirname(__file__), "src", "settings_yaml_default.h")

with open(src, "r", encoding="utf-8") as f:
    lines = f.readlines()

parts = []
parts.append("/* AUTO-GENERATED by gen_settings_default.py — do not edit */\n")
parts.append("#pragma once\n")
parts.append("static const char k_settings_yaml_default[] =\n")
for line in lines:
    escaped = line.rstrip("\n").replace("\\", "\\\\").replace('"', '\\"').replace("%", "%%")
    parts.append(f'    "{escaped}\\n"\n')
parts.append("    ;\n")

with open(dst, "w", encoding="utf-8") as f:
    f.writelines(parts)

print(f"[gen] {dst} written ({len(lines)} lines)")
