#!/bin/sh
# Convert .cso → C uint8_t array header.
out=src/shaders_embedded.h
echo "/* Auto-generated by tools_gen_shader_header.sh — do not edit. */" > "$out"
echo "#ifndef ME_SHADERS_EMBEDDED_H" >> "$out"
echo "#define ME_SHADERS_EMBEDDED_H" >> "$out"
echo "#include <stddef.h>" >> "$out"
for stage in vs ps; do
  f=src/shaders/quad_${stage}.cso
  name=quad_${stage}_bytecode
  echo "" >> "$out"
  echo "static const unsigned char ${name}[] = {" >> "$out"
  od -An -vtx1 "$f" | sed 's/ /,0x/g; s/^,/  /; s/$/,/' >> "$out"
  echo "};" >> "$out"
  echo "static const size_t ${name}_len = sizeof(${name});" >> "$out"
done
echo "" >> "$out"
echo "#endif" >> "$out"
echo "wrote $out ($(wc -c < "$out") bytes)"
