#!/bin/sh
# Compile Vulkan shaders to SPIR-V and emit a C header with embedded bytecode.
# Requires glslc (ships with the Vulkan SDK).
#
# Output: src/shaders_vk_embedded.h
set -e

if ! command -v glslc >/dev/null 2>&1; then
    echo "glslc not found on PATH. Install Vulkan SDK or add \$VULKAN_SDK/Bin to PATH." >&2
    exit 1
fi

out=src/shaders_vk_embedded.h
tmp=src/shaders/.tmp_spv

mkdir -p "$tmp"

echo "/* Auto-generated by tools_gen_spv_header.sh — do not edit. */"  > "$out"
echo "#ifndef ME_SHADERS_VK_EMBEDDED_H"                               >> "$out"
echo "#define ME_SHADERS_VK_EMBEDDED_H"                               >> "$out"
echo "#include <stddef.h>"                                            >> "$out"
echo "#include <stdint.h>"                                            >> "$out"

# pairs: stage:input:name
for spec in vert:quad.vert:quad_vert_spv frag:quad.frag:quad_frag_spv; do
    stage=${spec%%:*}
    rest=${spec#*:}
    src_name=${rest%%:*}
    name=${rest#*:}

    glslc -fshader-stage=$stage "src/shaders/$src_name" -o "$tmp/$name.spv"

    echo ""                                                            >> "$out"
    echo "/* SPIR-V for src/shaders/$src_name */"                      >> "$out"
    echo "static const uint32_t ${name}[] = {"                         >> "$out"
    # Emit one uint32_t per entry. SPIR-V is little-endian sequence of u32.
    # SPIR-V is a stream of little-endian uint32. `od -An -v -tx4` emits four
    # hex words separated by spaces; we turn each into 0xXXXXXXXX, comma-sep.
    od -An -v -tx4 -w16 "$tmp/$name.spv" \
      | awk '{ for (i=1;i<=NF;i++) printf "  0x%s,\n", $i }' >> "$out"
    echo "};"                                                          >> "$out"
    echo "static const size_t ${name}_len = sizeof(${name});"          >> "$out"
done

echo ""                                                                >> "$out"
echo "#endif"                                                          >> "$out"

rm -rf "$tmp"
echo "wrote $out ($(wc -c < "$out") bytes)"
